### ISSUE TITLE
Origin API, submit_job definition improvements.

### ISSUE THREAD

**Issue by oguzhanogreden** [roctoproject/rocto-docs#1]
`origin.json` defines the `submit_job` interface for the server. Currently, server expects a a JSON with two items: `meta` and `content`. `meta` has shared content with the `meta.json` created by rocto-rpackage.

We could remove the shared content so that server can read from the rpackage as needed. This would create server load. So I suggest we match these two definitions. Then client can add what needs to be added. We prevent repetition of work and possible tiny little mistakes.

Since this requires a reworking of the server side API, this is for you @vankesteren :)

**Comment by vankesteren** [comment]
Do you mean we should completely equalise the api `meta` content with the `meta.json` in the `.rocto` file?

**Comment by oguzhanogreden** [comment]
Yes, to start with. At the moment there are items with different keys, refering to the same value. For instance, `RPackages` in `meta.json` and `packages` in `submit_file['meta']` specification in API. 

After this, if there are things that can only be provided by origin, we can of course append them in API.

**Comment by oguzhanogreden** [comment]
In addition, we decided to have the following feature: Users can select from which conditions to be run from the grid of simulation parameters in client. This is implemented in the client at the moment.

We need to specify the API for this too.

**Comment by vankesteren** [comment]
Alright! And that's also why I got the 'wrong API version' error upon trying to submit a job from the client, I assume?

**Comment by oguzhanogreden** [comment]
As far as I remember that is because `meta` content sent by client doesn't match API. I remember seeing that server tries to look something up and fails.

**Comment by vankesteren** [comment]
# Here are my suggestions
Could you read through it and see if you agree? Anything not in the R `meta.json` then needs to be added by the client (`importer.py` line `206`). If you agree, I'll update the R package as well as the server to account for these changes!

# Original api

## JSON (origin)
```json
"submit_job": {
    "meta": {
      "version": "Character of api version",
      "jobId":  "Generated unique string based on username and time + hash",
      "user": "Unique username",
      "numTasks": "Integer of the number of tasks in the job",
      "fileSize": "Numeric of the file size in bytes",
      "notify": "Character for now (none/email/something)",
      "requirements": {
        "memory": "Integer of estimated ram in MB",
        "cpuTime": "Integer of seconds",
        "packages": [
          { 
            "name": "Character of package name",
            "version": "Character of version",
            "repo": "CRAN"
          },
          { 
            "name": "Character of package name",
            "version": "Character of version",
            "repo": "CRAN"
          }
        ],
        "RVersion": "Character of R version",
        "cores": "Integer of core count, always 1 for now"
      }
    },
    "content": "buffer of zipped folder"
  }
```

## R
```R
 meta <- list(
    "version" = "0.1.0",
    "nParams" = ncol(grid), 
    "params" = colnames(grid),
    "testParams" = gridEnv[["testParams"]],
    "nIter" = nrow(grid),
    "dataSize" = .folderSize(file.path(fulldir, "data")),
    "memorySize" = prof[["outputSize"]],
    "cpuTime" = prof[["timeRequired"]],
    "RInfo" = as.list(unlist(version)),
    "RPackages" = .findUsedPackages(file.path(fulldir, "main.R"))
  )
```

# Suggested changes
In JSON (client/server):
- [ ] Rename RVersion to RInfo and equalise it to R list output.
- [ ] Rename memory -> memorySize

In R (package):
- [ ] Remove "nParams", "params", "nIter", "testParams"
- [ ] Rename "RPackages" -> "packages"

- [ ] Create sublist "requirements" with
  - [ ] memorySize
  - [ ] cpuTime
  - [ ] packages
  - [ ] RInfo
  - [ ] cores

# Result
## JSON (origin)
```json
"submit_job": {
    "meta": {
      "version": "Character of api version",
      "jobId":  "Generated unique string based on username and time + hash",
      "user": "Unique username",
      "numTasks": "Integer of the number of tasks in the job",
      "fileSize": "Numeric of the file size in bytes",
      "notify": "Character for now (none/email/something)",
      "requirements": {
        "memorySize": "Integer of estimated ram in MB",
        "cpuTime": "Integer of seconds",
        "packages": [
          { 
            "name": "Character of package name",
            "version": "Character of version",
            "repo": "CRAN"
          },
          { 
            "name": "Character of package name",
            "version": "Character of version",
            "repo": "CRAN"
          }
        ],
        "RInfo": "JSON of R info obtained by JSONifying R command 'as.list(unlist(version))'",
        "cores": "Integer of core count, always 1 for now"
      }
    },
    "content": "buffer of zipped folder"
  }
```


## R
```R
  meta <- list(
    "version" = "0.1.0",
    "requirements" = list(
      "memorySize" = prof[["outputSize"]],
      "cpuTime" = prof[["timeRequired"]],
      "packages" = .findUsedPackages(file.path(fulldir, "main.R")),
      "RInfo" = as.list(unlist(version)),
      "cores" = .findNCores(file.path(fulldir, "main.R")) # return 1 for now
    )
  )
```

**Comment by vankesteren** [comment]
I just realised that we should add stuff to the json api from the origin to the server based on your slack suggestions @oguzhanogreden. Maybe you can make a similar proposal?

**Comment by oguzhanogreden** [comment]
Let's revive this.

submit_job should have an element for `selectedTasks` element.

## JSON Origin
```
"submit_job": {
[...]
    "content": "buffer of zipped folder",
    "selectedTasks": "Integer vector of row indices of the grid rows.
  }
```

**Comment by vankesteren** [comment]
Indices will start at 1?

**Comment by oguzhanogreden** [comment]
Nope, at 0.

**Comment by vankesteren** [comment]
let's put it in the meta instead of `numTasks` though:

```js
"submit_job": {
  "meta": {
    "version": "Character of api version",
    "jobId":  "Generated unique string based on username and time + hash",
    "user": "Unique username",
→ → "selectedTasks": "Integer vector of row indices of the task grid rows",
    "fileSize": "Numeric of the file size in bytes",
    [...]
}
```

**Comment by vankesteren** [comment]
and we should bump the api version

**Comment by oguzhanogreden** [comment]
Well, I wrote "fix" and Github closed this automatically. What do you think?

**Comment by vankesteren** [comment]
👍
